### ISSUE TITLE
Error: Mednafen version is not supported. You need 0.9.41 version or above.

### ISSUE THREAD

**Issue by corvusd** [AmatCoder/mednaffe#52]
Hello community and thanks developers,

I wanted to be able to use your frontend on my Ubuntu 16.04 64bit.
I downloaded mednafen 0.9.42 and I have compiled it installed on my system correctly. I have the folder and file .mednafen / mednafen-09x.cfg
But both the mednaffe version 0.8.4 stable as the master of git. I get the same error:
Error: Mednafen version is not supported.
You need 0.9.41 version or above.
What am I doing wrong?
Thanks for the help! :)

David Gámiz Jiménez

**Comment by AmatCoder** [comment]
Have you an older mednafen emulator installed? Maybe from Ubuntu repositories?

Note that Ubuntu 16.04 has 0.9.38.7 version. You can search for executable in /usr/games

**Comment by corvusd** [comment]
No, I'm not using the repository version.
Sorry, maybe I have not explained well before. I wanted to say, I downloaded the source code of the latest version and I compile it and install it in my system, attached capture terminal:
![seleccion_518](https://cloud.githubusercontent.com/assets/10695292/22861181/b9f45c18-f112-11e6-8b3b-e78c222387b0.jpg)

On the other hand I do not have this file: ./config/mednaffe.conf

That could be happening? Thanks in advance! :)

**Comment by AmatCoder** [comment]
Ops! I see now...Localization is the culprit.

Mednaffe search for version comparing numbers in english output: "Starting Mednafen 0.9.42"
And as they are not in the same place it fails.
This is a bug. Thanks for reporting.

(As workaround you can change temporarily your system to english into System Settings > Language & Text > Language)

**Comment by corvusd** [comment]
Yes, putting the language system in English, mednaffe run properly.
Whit:  $ LANG=en_US.UTF-8 mednaffe ; Not run

**Comment by AmatCoder** [comment]
Fixed on 8d99d6c commit.

**Comment by padremayi** [comment]
Starting Mednaffe 0.8.6
Mednafen 09x configuration file found.
Error: Mednafen version is not compatible.
You need 0.9.41 version or above.

Mednafen version is 0.9.45.1

The problem is still present

**Comment by AmatCoder** [comment]
copied from [here](https://github.com/AmatCoder/mednaffe/issues/33#issuecomment-385558913):

@cpcbegin

Debian 9 contains an old version of mednaffe (0.8.4) in repositories.
This version had a bug (issue #52 ) when certain localizations (i.e. spanish) are used.
**It was fixed in 0.8.5 version.**

A workaround is to run "LANG=C mednaffe" in a terminal.

You can read the Debian bug report [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890482).
